plugins {
  id 'org.gradle.toolchains.foojay-resolver-convention' version '0.10.0'
}
include ':app'

def airSubModulePath = settings.ext.find('airSubModulePath')

def subModules = [
  "WalletNative",
  "Icons",
  "UIComponents",
  "UICreateWallet",
  "UISwap",
  "WalletContext",
  "WalletCore",
  "WalletSDK",
  "UISettings",
  "UIPasscode",
  "UIHome",
  "UIPortfolio",
  "UIAssets",
  "UIBrowser",
  "UITransaction",
  "OverScroll",
  "UISend",
  "UIInAppBrowser",
  "AirAsFramework",
  "QRScan",
  "UIReceive",
  "UITonConnect",
  "UIWalletConnectPay",
  "Ledger",
  "UIWidgets",
  "UIWidgetsConfigurations",
  "WalletBaseContext",
]
include(airSubModulePath)
project(airSubModulePath).projectDir = file('air/SubModules')

include("$airSubModulePath:vkryl:core")
include("$airSubModulePath:vkryl:android")

subModules.each { moduleName ->
  include "${airSubModulePath}:${moduleName}"
  project("${airSubModulePath}:${moduleName}").name = moduleName
}
