name: Test

on:
  push:
    branches:
      - production
  pull_request:

jobs:
  test:
    name: Simple tests
    if: github.repository == 'torganization-ae/twallet'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: |
          npm run i18n:build:default
          npm test
